global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'backend_service'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'backend_service'
    static_configs:
      - targets: ['node-exporter:9100']
